#!/bin/bash
dir="/var/www/html/Animo-Backend"
if [ ! -d "$dir" ]; then
	gcloud secrets versions access latest --secret=backend_id_rsa >> ~/.ssh/id_rsa;
	gcloud secrets versions access latest --secret=backend_id_rsa_pub >> ~/.ssh/id_rsa.pub;
	chmod 600 ~/.ssh/id_rsa;
	chmod 600 ~/.ssh/id_rsa.pub;
	cd /var/www/html/;
	sudo chown -R mngoga:mngoga /var/www/;
	ssh-keyscan github.com >> ~/.ssh/known_hosts;
	eval $(ssh-agent);
	ssh-add ~/.ssh/id_rsa;
	git clone git@github.com:Astra-Innovations/Animo-Backend.git;
	cd /var/www/html/Animo-Backend/backend;
	git checkout;
	git pull;
	python -m venv env;
	source env/bin/activate;
	pip install -r requirements.txt --use-pep517;
	cd /var/www/html/Animo-Backend/backend/astra;
	chmod u+x /var/www/html/Animo-Backend/backend/astra/vm_creation_script.py;
	chmod u+x /var/www/html/Animo-Backend/backend/astra/vm_startup_script.py;
	chmod u+x /var/www/html/Animo-Backend/backend/astra/update_file_permissions.py;
	chmod u+x /var/www/html/Animo-Backend/backend/astra/vm_restart_crons.py;
	sleep 2;
	/var/www/html/Animo-Backend/backend/astra/update_file_permissions.py;
	sleep 2;
	/var/www/html/Animo-Backend/backend/astra/vm_creation_script.py;
	sudo chmod u+x /etc/systemd/system/vm_startup_script.service;
	sudo systemctl daemon-reload;
	sudo systemctl enable vm_startup_script.service;
	sudo systemctl start vm_startup_script.service;
	sh -c "echo \"MACHINE_TYPE='Backend Middleware'\" >> /var/www/html/Animo-Backend/backend/astra/.env";
	sh -c "echo \"DEPLOYMENT_TIER='TESTING'\" >> /var/www/html/Animo-Backend/backend/astra/.env";
	sh -c "echo \"PARTNER_ID=12\" >> /var/www/html/Animo-Backend/backend/astra/.env";
	sh -c "echo \"WITSML_CONNECTION_ID=3\" >> /var/www/html/Animo-Backend/backend/astra/.env";
	sudo chown -R www-data:www-data /var/www/html/;
	sudo a2enmod headers;
	sudo a2enmod rewrite;
	sudo a2enmod proxy_http;
	sudo service apache2 restart;
	sudo a2enmod ssl;
	sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/apache-selfsigned.key -out /etc/ssl/certs/apache-selfsigned.crt -subj "/C=US/ST=Texas/L=Houston/O=My Organization/OU=My Department/CN=animo-ap.pro/emailAddress=contact@astra-ai.com";
	sudo a2ensite 000-default-ssl;
	sudo service apache2 restart;
	# sudo gsutil cp gs://animo-external-data/falcon-sensor_6.53.0-15003_amd64.deb /etc/falcon-sensor_6.53.0-15003_amd64.deb;
	# sudo dpkg -i /etc/falcon-sensor_6.53.0-15003_amd64.deb;
	# sudo /opt/CrowdStrike/falconctl -s --cid=585B97ED1AAE4F56BECB765BB7FE20DE-4F;
	# sudo service falcon-sensor start;
	# sudo /opt/CrowdStrike/falconctl -s --tags="Backend,Testing";
	# sudo systemctl restart falcon-sensor;
	sudo timedatectl set-timezone America/Chicago;
fi
